const $=s=>document.querySelector(s),modal=$('#modal');
let best=Number(localStorage.getItem('ball-crash-best')||0);
const menu=$('#menuScreen'),gameScreen=$('#gameScreen'),canvas=$('#game'),ctx=canvas.getContext('2d');
const COLORS=['#42ff79','#3be8ff','#8e63ff','#ffcc45','#ff5b7f','#ff8d45','#ff4cf0'];
let targets=[],shot=null,particles=[],floaters=[],score=0,nextValue=1,nextPower=null,turn=0,combo=0,aiming=false,aimX=0,aimY=0,last=0,raf=0,running=false,scale=1,gameOver=false;
$('#best').textContent=String(best).padStart(2,'0');
const buzz=(ms=18)=>{if(navigator.vibrate&&localStorage.getItem('haptics')!=='off')navigator.vibrate(ms)};
function open(label,title,body){buzz();$('#modalLabel').textContent=label;$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;modal.showModal()}
$('#how').onclick=()=>open('QUICK GUIDE','HOW TO PLAY','<ol><li>Drag from the top launcher toward the stack, then release to shoot.</li><li>Hit an equal number to merge it. Nearby matches create chain reactions.</li><li>Bomb shots clear a cluster. Wild shots merge with any number.</li><li>Every few shots the stack advances. Keep every ball below the warning line.</li></ol>');
$('#scores').onclick=()=>open('PERSONAL RECORD','HIGH SCORE',`<div class="score">${best}</div><p class="tagline">Your best run so far. Build chains to multiply every merge.</p>`);
$('#settings').onclick=()=>open('GAME OPTIONS','SETTINGS','<div class="setting"><span>Sound effects</span><button class="toggle" data-key="sound">ON</button></div><div class="setting"><span>Haptics</span><button class="toggle" data-key="haptics">ON</button></div>');
$('.close').onclick=()=>modal.close();modal.onclick=e=>{if(e.target===modal&&!gameOver)modal.close();const t=e.target.closest('.toggle');if(t){const on=t.textContent==='ON';t.textContent=on?'OFF':'ON';t.style.background=on?'#343a47':'var(--green)';localStorage.setItem(t.dataset.key,on?'off':'on');buzz()}};
$('#sound').onclick=e=>{const b=e.currentTarget,on=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',String(on));localStorage.setItem('sound',on?'on':'off');buzz()};

function resize(){const r=canvas.parentElement.getBoundingClientRect();scale=Math.min(devicePixelRatio||1,2);canvas.width=Math.floor(r.width*scale);canvas.height=Math.floor(r.height*scale);canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';ctx.setTransform(scale,0,0,scale,0,0)}
function size(){return{w:canvas.width/scale,h:canvas.height/scale}}
function radius(){return Math.min(27,size().w*.07)}
function launcher(){return{x:size().w/2,y:38}}
function reset(){score=0;turn=0;combo=0;shot=null;particles=[];floaters=[];nextValue=1;nextPower=null;gameOver=false;const host=location.hostname,testPower=new URLSearchParams(location.search).get('testPower');if((host==='127.0.0.1'||host==='localhost')&&(testPower==='bomb'||testPower==='wild'))nextPower=testPower;const{w,h}=size(),r=radius();targets=[{x:w*.15,y:h-r-15,v:1},{x:w*.32,y:h-r-15,v:2},{x:w*.70,y:h-r-15,v:3},{x:w*.87,y:h-r-15,v:3},{x:w*.18,y:h-r*3-25,v:1}].map(o=>({...o,r}));updateHud();$('#tutorial').classList.remove('gone')}
function start(){menu.hidden=true;gameScreen.hidden=false;resize();reset();running=true;last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function stop(){running=false;cancelAnimationFrame(raf);gameScreen.hidden=true;menu.hidden=false;$('#best').textContent=String(best).padStart(2,'0');if(modal.open)modal.close()}
function updateHud(){const next=$('#nextBall'),status=$('#status');$('#score').textContent=score;$('#gameBest').textContent=best;next.className=nextPower?`power-${nextPower}`:'';next.textContent=nextPower?(nextPower==='bomb'?'B':'W'):nextValue;next.setAttribute('aria-label',nextPower?`${nextPower} power-up ready`:`Next ball ${nextValue}`);next.style.background=nextPower?(nextPower==='bomb'?'linear-gradient(135deg,#ffcc45,#ff4f68)':'linear-gradient(135deg,#ff4cf0,#8e63ff,#3be8ff)'):COLORS[(nextValue-1)%COLORS.length];status.textContent=nextPower?`${nextPower.toUpperCase()} READY`:combo>1?`CHAIN x${combo}`:`POWER IN ${5-turn%5} Â· ROW IN ${3-turn%3}`}
function pointer(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function down(e){if(shot||gameOver)return;e.preventDefault();aiming=true;const p=pointer(e);aimX=p.x;aimY=p.y;$('#tutorial').classList.add('gone')}
function move(e){if(!aiming)return;e.preventDefault();const p=pointer(e);aimX=p.x;aimY=p.y}
function up(){if(!aiming||shot||gameOver)return;aiming=false;const o=launcher();let dx=aimX-o.x,dy=aimY-o.y;if(dy<45)dy=190;const len=Math.hypot(dx,dy)||1,speed=620;shot={x:o.x,y:o.y,r:nextPower?13:10,vx:dx/len*speed,vy:dy/len*speed,v:nextValue,power:nextPower,age:0};nextPower=null;nextValue=1+Math.floor(Math.random()*Math.min(4,2+Math.floor(score/20)));combo=0;updateHud();buzz()}
canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);window.addEventListener('pointerup',up);

function burst(x,y,color,n=12){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=50+Math.random()*150;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.7,color})}}
function addScore(x,y,value){combo++;const gained=value*combo;score+=gained;floaters.push({x,y,text:`+${gained}${combo>1?'  x'+combo:''}`,life:1});if(score>best){best=score;localStorage.setItem('ball-crash-best',best)}updateHud()}
function chainMerge(index){let current=targets[index],merged=true;while(merged&&current){merged=false;for(let i=targets.length-1;i>=0;i--){const other=targets[i];if(other===current||other.v!==current.v)continue;const d=Math.hypot(other.x-current.x,other.y-current.y);if(d<current.r+other.r+18){current.x=(current.x+other.x)/2;current.y=(current.y+other.y)/2;targets.splice(i,1);current.v++;current.r=Math.min(current.r+2,36);addScore(current.x,current.y,current.v);burst(current.x,current.y,COLORS[(current.v-1)%COLORS.length],16);merged=true;buzz(32);break}}}}
function attachShot(x,y){if(!shot)return;if(shot.power){shot=null;endTurn();return}const r=radius(),t={x:Math.max(r,Math.min(size().w-r,x)),y:Math.max(r+10,Math.min(size().h-r-8,y)),r,v:shot.v};targets.push(t);shot=null;settleBoard();endTurn()}
function bombBlast(x,y){const range=112,hit=targets.filter(t=>Math.hypot(t.x-x,t.y-y)<range),points=hit.reduce((sum,t)=>sum+t.v,0)*2;targets=targets.filter(t=>!hit.includes(t));score+=points;floaters.push({x,y,text:`BOOM +${points}`,life:1.2});burst(x,y,'#ffcc45',34);burst(x,y,'#ff4f68',26);if(score>best){best=score;localStorage.setItem('ball-crash-best',best)}shot=null;buzz(70);settleBoard();endTurn()}
function hitTarget(){if(!shot)return false;for(let i=targets.length-1;i>=0;i--){const t=targets[i],dx=shot.x-t.x,dy=shot.y-t.y,d=Math.hypot(dx,dy);if(d<shot.r+t.r){const nx=dx/(d||1),ny=dy/(d||1);if(shot.power==='bomb'){bombBlast(t.x,t.y);return true}if(shot.power==='wild'||shot.v===t.v){t.v++;t.r=Math.min(t.r+2,36);shot=null;addScore(t.x,t.y,t.v);burst(t.x,t.y,COLORS[(t.v-1)%COLORS.length],18);buzz(38);chainMerge(i);settleBoard();endTurn()}else attachShot(t.x+nx*(t.r+radius()+2),t.y+ny*(t.r+radius()+2));return true}}return false}
function settleBoard(){const{w,h}=size();for(let pass=0;pass<8;pass++){for(const t of targets){t.x=Math.max(t.r,Math.min(w-t.r,t.x));t.y=Math.min(h-t.r-8,t.y);for(const o of targets){if(o===t)continue;const dx=t.x-o.x,dy=t.y-o.y,d=Math.hypot(dx,dy),min=t.r+o.r+2;if(d<min&&d>0){const push=(min-d)/2;t.x+=dx/d*push;t.y+=dy/d*push}}}}}
function addRow(){const{w,h}=size(),r=radius();targets.forEach(t=>t.y-=r*1.75);const count=3+Math.min(2,Math.floor(score/35));for(let i=0;i<count;i++){const x=r+(i+.5)*(w-r*2)/count+(Math.random()-.5)*12,v=1+Math.floor(Math.random()*Math.min(4,2+score/25));targets.push({x,y:h-r-8,r,v})}settleBoard();burst(w/2,h-12,'#3be8ff',20)}
function endTurn(){turn++;if(turn%3===0)addRow();if(turn%5===0)nextPower=turn%10===0||score>=45&&turn%10===5?'wild':'bomb';updateHud();checkGameOver()}
function checkGameOver(){const danger=118;if(targets.some(t=>t.y-t.r<danger)){gameOver=true;aiming=false;shot=null;running=false;cancelAnimationFrame(raf);buzz(100);open('RUN COMPLETE','GAME OVER',`<div class="score">${score}</div><p class="tagline">Best ${best} &middot; ${turn} shots survived</p><button class="play again" id="playAgain"><span><small>TRY</small>AGAIN</span><b>&#8635;</b></button>`);$('#playAgain').onclick=()=>{modal.close();running=true;resize();reset();last=performance.now();raf=requestAnimationFrame(loop)}}}
function physics(dt){const{w,h}=size();if(shot){shot.age+=dt;shot.vy+=70*dt;shot.x+=shot.vx*dt;shot.y+=shot.vy*dt;if(shot.x<shot.r){shot.x=shot.r;shot.vx=Math.abs(shot.vx)*.94}if(shot.x>w-shot.r){shot.x=w-shot.r;shot.vx=-Math.abs(shot.vx)*.94}if(shot.y<shot.r){shot.y=shot.r;shot.vy=Math.abs(shot.vy)*.9}if(hitTarget())return;if(shot&&shot.y>h+25){shot=null;endTurn()}else if(shot&&shot.age>6)attachShot(shot.x,Math.min(shot.y,h-radius()-8))}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=160*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);for(const f of floaters){f.y-=35*dt;f.life-=dt}floaters=floaters.filter(f=>f.life>0)}
function circle(x,y,r,v){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=COLORS[(v-1)%COLORS.length];ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=14;ctx.fill();ctx.shadowBlur=0;ctx.fillStyle=v===3?'#fff':'#080a0f';ctx.font=`900 ${Math.max(19,r)}px 'Barlow Condensed',sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(v,x,y+1)}
function powerBall(x,y,r,type){const gradient=ctx.createRadialGradient(x-r*.3,y-r*.3,2,x,y,r);if(type==='bomb'){gradient.addColorStop(0,'#fff2a3');gradient.addColorStop(.34,'#ffc13d');gradient.addColorStop(1,'#ff405f')}else{gradient.addColorStop(0,'#ff9eed');gradient.addColorStop(.42,'#b45cff');gradient.addColorStop(1,'#3be8ff')}ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=gradient;ctx.shadowColor=type==='bomb'?'#ff6b45':'#a85cff';ctx.shadowBlur=24;ctx.fill();ctx.shadowBlur=0;ctx.beginPath();ctx.arc(x,y,r*.68,0,Math.PI*2);ctx.fillStyle='rgba(8,10,15,.34)';ctx.fill();ctx.strokeStyle='rgba(255,255,255,.65)';ctx.lineWidth=Math.max(1.5,r*.1);ctx.stroke();ctx.fillStyle='#fff';ctx.font=`900 ${Math.max(10,r*.9)}px Inter,sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(type==='bomb'?'B':'W',x,y+1)}
function trajectory(){const{w}=size(),o=launcher(),dx=aimX-o.x,dy=Math.max(aimY-o.y,45),len=Math.hypot(dx,dy)||1;let x=o.x,y=o.y,vx=dx/len*26,vy=dy/len*26;for(let i=1;i<19;i++){x+=vx;y+=vy;if(x<8||x>w-8)vx*=-1;ctx.beginPath();ctx.arc(x,y,Math.max(2,5-i*.16),0,Math.PI*2);ctx.fillStyle=`rgba(255,255,255,${1-i/22})`;ctx.fill()}}
function draw(){const{w,h}=size(),o=launcher();ctx.clearRect(0,0,w,h);ctx.strokeStyle='#ffffff0b';ctx.lineWidth=1;for(let y=24;y<h;y+=42){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.setLineDash([7,7]);ctx.strokeStyle='#ff5b7f88';ctx.beginPath();ctx.moveTo(0,118);ctx.lineTo(w,118);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#ff5b7faa';ctx.font='800 9px Inter';ctx.textAlign='left';ctx.fillText('DANGER',10,108);if(aiming&&!shot)trajectory();for(const t of targets)circle(t.x,t.y,t.r,t.v);if(shot){shot.power?powerBall(shot.x,shot.y,shot.r,shot.power):circle(shot.x,shot.y,shot.r,shot.v)}else if(!gameOver){nextPower?powerBall(o.x,o.y,15,nextPower):circle(o.x,o.y,11,nextValue)}if(!shot&&!gameOver){ctx.beginPath();ctx.arc(o.x,o.y,23,0,Math.PI*2);ctx.strokeStyle=nextPower?'#ffffffaa':'#ffffff55';ctx.lineWidth=2;ctx.setLineDash([2,4]);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(o.x,o.y,30,0,Math.PI*2);ctx.strokeStyle='#ffffff16';ctx.lineWidth=1;ctx.stroke();if(nextPower){ctx.fillStyle='#dfe5f3';ctx.font='800 8px Inter,sans-serif';ctx.textAlign='center';ctx.fillText(`${nextPower.toUpperCase()} SHOT`,o.x,o.y+42)}}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/.7);ctx.fillStyle=p.color;ctx.fillRect(p.x-2,p.y-2,4,4)}ctx.globalAlpha=1;for(const f of floaters){ctx.globalAlpha=Math.max(0,f.life);ctx.fillStyle='#fff';ctx.font='900 17px Barlow Condensed';ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y)}ctx.globalAlpha=1}
function loop(now){if(!running)return;const dt=Math.min((now-last)/1000,.025);last=now;physics(dt);draw();raf=requestAnimationFrame(loop)}
$('#play').onclick=start;$('#menuButton').onclick=stop;$('#restart').onclick=reset;window.addEventListener('resize',()=>{if(running){resize();reset()}});
